//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HexEditor.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_MYBUTTON_PREVIOUS           103
#define IDC_MYBUTTON_NEXT               104
#define IDR_MAINFRAME                   128
#define IDR_FILETYPE                    129
#define IDD_INSERTDATA                  130
#define IDR_CONTEXT                     131
#define IDD_EDITDATA                    132
#define IDD_PROGRESS                    133
#define IDD_FORMATVIEW                  134
#define IDD_DMD                         135
#define IDB_BITMAP_PIXEL_BLACK          136
#define IDB_BITMAP_PIXEL_YELLOWDIM      137
#define IDB_BITMAP_PIXEL_YELLOWMEDIUM   138
#define IDB_BITMAP_PIXEL_YELLOWBRIGHT   139
#define IDB_BITMAP_PIXEL_GREYDIM        142
#define IDB_BITMAP_PIXEL_GREYBRIGHT     143
#define IDB_BITMAP_PIXEL_GREENBRIGHT    144
#define IDB_BITMAP_PIXEL_GREENDIM       145
#define IDI_ICON28                      181
#define IDI_ICON29                      182
#define IDI_ICON30                      183
#define IDI_ICON31                      184
#define IDI_ICON32                      185
#define IDI_ICON33                      186
#define IDI_ICON34                      187
#define IDI_ICON35                      188
#define IDI_ICON36                      189
#define IDI_ICON37                      190
#define IDI_ICON38                      191
#define IDI_ICON39                      192
#define IDI_ICON40                      193
#define IDI_ICON41                      194
#define IDI_ICON42                      195
#define IDI_ICON43                      196
#define IDI_ICON44                      197
#define IDB_BITMAP_PIXEL_GREENMEDIUM    199
#define IDB_BITMAP_PIXEL_GREYMEDIUM     200
#define IDB_BITMAP_PIXEL_REDMEDIUM      201
#define IDB_BITMAP_PIXEL_REDBRIGHT      202
#define IDB_BITMAP_PIXEL_REDDIM         203
#define IDB_BITMAP_PIXEL_TEALDIM        204
#define IDB_BITMAP_PIXEL_TEALBRIGHT     205
#define IDB_BITMAP_PIXEL_TEALMEDIUM     206
#define IDB_BITMAP_PIXEL_BLUEDIM        207
#define IDB_BITMAP_PIXEL_BLUEBRIGHT     208
#define IDB_BITMAP_PIXEL_BLUEMEDIUM     209
#define IDB_BITMAP_PIXEL_VIOLETDIM      210
#define IDB_BITMAP_PIXEL_VIOLETBRIGHT   211
#define IDB_BITMAP_PIXEL_VIOLETMEDIUM   212
#define IDB_TRANSPARENT_SPLASH          223
#define IDD_ABOUT_LIMITATIONS           224
#define IDB_BITMAP_FULLDMD              225
#define IDD_REG                         226
#define IDD_NAG                         227
#define IDD_UNLOCK                      228
#define IDD_NAGDLG                      240
#define IDC_INSERTAMT                   1000
#define IDC_DATA                        1001
#define IDC_INPUT                       1002
#define IDC_PROGRESSBAR                 1003
#define IDC_TASK                        1004
#define IDC_MINIPROGRESSBAR             1005
#define IDC_ABORT                       1006
#define IDC_FVIEW                       1007
#define IDC_STATIC_USERREG              1009
#define IDC_BUTTON_NEXT_GRAPHIC         1012
#define IDC_BUTTON_PREVIOUS_GRAPHIC     1013
#define IDC_STATIC_MEDIUM               1014
#define IDC_STATIC_DMD1_TEXTBOX         1014
#define IDC_STATIC_DIM                  1015
#define IDC_STATIC_DMD2_TEXTBOX         1015
#define IDC_STATIC_BOTH                 1017
#define IDC_STATIC_DMD3_TEXTBOX         1017
#define IDC_CHECK_XORED                 1018
#define IDC_CHECK_SKIPPED               1019
#define IDC_STATIC_ABOUTICON            1020
#define IDC_LIST1                       1024
#define IDC_SPIN1                       1025
#define IDC_STATIC_MYINFO               1026
#define IDC_EDIT2                       1028
#define IDC_EDIT1                       1030
#define IDC_EDIT_NAGTEXT                1032
#define IDC_BUTTON_UNLOCK               1035
#define IDC_EDIT_UNLOCK                 1036
#define IDC_EDIT_LOCK                   1037
#define IDC_COMBO_USERNAMES             1040
#define IDC_CHECK1                      1042
#define IDC_STATICBOX                   1043
#define IDC_STATIC_VER                  1044
#define IDC_STATIC_CR                   1045
#define IDC_STATIC_DMD1_HEADER          1046
#define IDC_STATIC_DMD2_HEADER          1047
#define IDC_STATIC_DMD3_HEADER          1048
#define ID_EDIT_INSERT                  32771
#define ID_CONTEXT_INSERTBYTES          32772
#define ID_CONTEXT_EDITSTRING           32774
#define ID_CONTEXT_EDITINTEGER          32775
#define ID_CONTEXT_EDITHEX              32776
#define ID_VIEW_FORMAT                  32777
#define ID_VIEW_DMDGRAPHICS             32778
#define ID_VIEW_FONTDATA                32779
#define ID_EDIT_PATCHWPC_CHECKSUMFIXUP  32780
#define ID_EDIT_PATCHWPC_SECURITYPICINHIBIT 32781
#define ID_EDIT_PATCHWPC_INHIBITCREDITDOT 32782
#define ID_EDIT_PATCHWPC_INHIBITPRESSENTER 32783
#define ID_EDIT_GAMESPECIFIC_MEDIEVALMADNESS_ENABLEPROFANITYROM 32784
#define ID_EDIT_PATCHWPC_INHIBITFREEONLY 32785
#define ID_EDIT_GAMESPECIFIC_INDIANAJONES_NOHATE 32786
#define ID_EDIT_GAMESPECIFIC_INDIANAJONES_CORRECTARCARK 32787
#define ID_EDIT_GAMESPECIFIC_THESHADOW_FIXL6VOLUMEBUG 32788
#define ID_EDIT_GAMESPECIFIC_THESHADOW_FAMILYMODEII 32789
#define ID_EDIT_GAMESPECIFIC_THESHADOW_NOFLIPPERSNAG 32790
#define ID_EDIT_PATCHWPC_VERSIONNUMBER  32791
#define ID_EDIT_GAMESPECIFIC_BRIDEOFPINBOT_FIXRESETBUG 32792
#define ID_EDIT_GAMESPECIFIC_NOGOODGOPHERS_FIXALLBUGSIN 32793
#define ID_EDIT_SOUNDTABLE              32794
#define l                               32795
#define ID_EDIT_TEXTTABLE               32797
#define IDD_LIMITATIONS                 32798
#define ID_EDIT_PATCHWPC_QUICKBOOT      32799
#define ID_EDIT_GAMESPECIFIC_DEMOLITIONMAN_CREATEHA4ROM 32800
#define ID_EDIT_GAMESPECIFIC_INDIANAJONES_CREATEIJONEHK1 32801
#define ID_EDIT_GAMESPECIFIC_MEDIEVALMADNESS_CREATEMM109BH 32802
#define ID_EDIT_GAMESPECIFIC_MEDIEVALMADNESS_CREATEMM109CH 32803
#define ID_EDIT_GAMESPECIFIC_THESHADOW_CREATESHADHKH1 32804
#define ID_EDIT_GAMESPECIFIC_THESHADOW_CREATESHADHKH2 32805
#define ID_EDIT_GAMESPECIFIC_THESHADOW_CREATESHADHKH3 32806
#define ID_EDIT_GAMESPECIFIC_THESHADOW_CREATESHADHKH4 32807
#define ID_EDIT_GAMESPECIFIC_THESHADOW_CREATESHADHKH5 32808
#define ID_EDIT_GAMESPECIFIC_THESHADOW_CREATESHADHKH6 32809
#define ID_EDIT_GAMESPECIFIC_TWILIGHTZONE_CREATETZ94CH 32810
#define ID_EDIT_GAMESPECIFIC_CACTUSCANYON_ADDDMDMATCHGRAPHIC 32811
#define ID_VIEW_ANIMATIONDATA           32812
#define ID_EDIT_SWITCHMATRIXTABLE       32813
#define ID_INDICATOR_CLOCK              59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        243
#define _APS_NEXT_COMMAND_VALUE         32814
#define _APS_NEXT_CONTROL_VALUE         1049
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
